### ISSUE TITLE
Search for addresses just in a "Kanton" not working

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#9]
If you choose just a region (Kanton) and clicking on "Search" no results will come. It should display all items/addresses from the selected region/kanton.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Comment: We have checked here, it's working here. Please check following screenshots
Screenshot: http://prntscr.com/bgjq3a , http://prntscr.com/bgjqb9 , http://prntscr.com/bgjqdm

Can you please give us more test cases with your System configurations so that we can have more idea?

Regards.
